
services:
  lucy-db:
    image: pgvector/pgvector:pg15
    container_name: lucy_postgres
    restart: always
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lucy_db
    ports:
      - "5432:5432"
    volumes:
      - lucy_pgdata:/var/lib/postgresql/data

  lucy-tts:
    image: ghcr.io/remsky/kokoro-fastapi-cpu:latest
    container_name: kokoro-tts
    restart: always
    ports:
      - "8880:8880"

volumes:
  lucy_pgdata:
